---
title: "Endpoint Specification"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Endpoint Specification}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: sentence
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Overview

The endpoint specifications comprise a central input to {chef} as it contains the instructions to produce the statistics for endpoints.

The specifications contain instructions on *what* data to use for the endpoint, *what* statistics to include, *how* the statistics are calculated, *how* to group the population, and *what* criteria must be met to include the endpoint in the final dossier.

The specifications must be organized in a data table where each row contains an endpoint specification
These rows are processed independently and may represent one of more endpoints. 
One single specification may contain instructions to produce multiple endpoints for e.g. different severity levels or system organ classes.

The result of processing the endpoint specifications through {chef} is a set of statistics, which are structured in a long-formatted data table that can be further processed by downstream modules that e.g. format the raw results to endpoint tables. This is out of scope of {chef}.

Many of the components in the endpoint specifications consist of references to custom functions outside {chef}, which provide high flexibility in defining the endpoints.
Both the endpoint specifications and associated custom functions must be supplied by the user as inputs to {chef} and is not a part of the package. 

The endpoint definition is created by calling the function `mk_endpoint_str`. Some endpoint parameters are required while others are optional. Optional parameters are by default set to empty when calling `mk_endpoint_str`, so that the user does not have to type all endpoint parameters every time but only those that are required and relevant to each endpoint specification.

In summary, the endpoint specifications can be considered a cooking recipe that along with a set of ingredients (the trial data) and the cooking tools (the custom functions) are handed over to the chef, {chef}, that prepares the endpoints. 

For more details on the internal steps of {chef} see [Getting Started with Pipelines](targets_gettingstarted.html).

# Components

The parameters of each endpoint specification can be grouped in to the sets below, which are explained in their respective sections:

<table border="1">
    <tr>
        <th>Type</th>
        <th>Section</th>
        <th>Endpoint parameter</th>
    </tr>
    <tr>
        <td rowspan="13">Population and outcome specifications</td>
        <td rowspan="2">[ADaM data](ep_spec_adam_data.html). What data to use and how to consolidate it into a single data table for the endpoint that is used to calculate statistics.</td>
        <td>`study_metadata`</td>
    </tr>
    <tr>
        <td>`data_prepare`</td>
    </tr>
    <tr>
        <td rowspan="2">[Treatment arms](ep_spec_treatment_arms.html). Which variable contains marking of the treatment arms and what is the reference/intervention treatment arm.</td>
        <td>`treatment_var`</td>
    </tr>
    <tr>
        <td>`treatment_refval`</td>
    </tr>
    <tr>
        <td rowspan="3">[Analysis population](ep_spec_population_def.html). How to filter the data to the analysis population for the endpoint.</td>
        <td>`pop_var`</td>
    </tr>
    <tr>
        <td>`pop_value`</td>
    </tr>
    <tr>
        <td>`custom_pop_filter`</td>
    </tr>
    <tr>
        <td rowspan="4">[Endpoint events](ep_spec_event_def.html). How to define events for the endpoint.</td>
        <td>`period_var`</td>
    </tr>
    <tr>
        <td>`period_value`</td>
    </tr>
    <tr>
        <td>`endpoint_filter`</td>
    </tr>
    <tr>
        <td>`group_by`</td>
    </tr>
    <tr>
        <td rowspan="1">[Strata](ep_spec_strata_def.html). How to slice the data within the endpoint.</td>
        <td>`stratify_by`</td>
    </tr>
     <tr>
        <td rowspan="1">[Endpoint label](ep_spec_label.html). What events the endpoint describes.</td>
        <td>`endpoint_label`</td>
    </tr>
    <tr>
        <td rowspan="6">Methods</td>
        <td rowspan="3">[Criteria methods](methods_criteria.html). Requirements that must be met to include different types of statistics in the endpoint results.</td>
        <td>`crit_endpoint`</td>
    </tr>
    <tr>
        <td>`crit_by_strata_by_trt`</td>
    </tr>
    <tr>
        <td>`crit_by_strata_across_trt`</td>
    </tr>
    <tr>
        <td rowspan="3">[Statistical methods](methods_stat.html). Statistical methods to apply in the endpoint.</td>
        <td>`stat_by_strata_by_trt`</td>
    </tr>
    <tr>
        <td>`stat_by_strata_across_trt`</td>
    </tr>
    <tr>
        <td>`stat_across_strata_across_trt`</td>
    </tr>
</table>
