name: PR cleanup

on:
  pull_request:
    types: [closed, synchronize]

jobs:
  delete_pr_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete PR artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete-all -R ${{ github.repository }} --confirm
